### ISSUE TITLE
exception when running etwanalyzer.exe

### ISSUE THREAD

**Issue by wtjwtjwtj** [Siemens-Healthineers/ETWAnalyzer#39]
**Describe the bug**
exception when running etwanalyzer.exe
```
D:\WS\EtwAnalysis\CtAnalyzers\bin\Release>ETWAnalyzer.exe -dump CPU -filedir D:\Etw-Extract -debug

Error: Process renaming XML file not found. D:\WS\EtwAnalysis\CtAnalyzers\bin\Release\Configuration\ProcessRenameRules.xml Check D:\WS\EtwAnalysis\CtAnalyzers\bin\Release\ETWAnalyzer_Trace.log for full details, or use -debug switch to get full output.
System.IO.FileNotFoundException: Process renaming XML file not found. D:\WS\EtwAnalysis\CtAnalyzers\bin\Release\Configuration\ProcessRenameRules.xml
   at ETWAnalyzer.Extract.ProcessRenamer.LoadProcessRenamer() in D:\a\ETWAnalyzer\ETWAnalyzer\ETWAnalyzer\Extract\ProcessRenamer\ProcessRenamer.cs:line 49
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at ETWAnalyzer.Extract.ETWProcess.get_ProcessNamePretty() in D:\a\ETWAnalyzer\ETWAnalyzer\ETWAnalyzer\Extract\ETWProcess.cs:line 77
   at ETWAnalyzer.Extract.ETWProcess.GetProcessWithId(Boolean usePrettyProcessName) in D:\a\ETWAnalyzer\ETWAnalyzer\ETWAnalyzer\Extract\ETWProcess.cs:line 43
   at ETWAnalyzer.EventDump.DumpFileDirBase`1.IsMatchingProcessAndCmdLine(TestDataFile file, ProcessKey process) in D:\a\ETWAnalyzer\ETWAnalyzer\ETWAnalyzer\EventDump\DumpFileDirBase.cs:line 632
   at ETWAnalyzer.EventDump.DumpCPUMethod.<>c__DisplayClass98_0.<AddAndPrintTotalStats>g__ProcessFilter|0(KeyValuePair`2 procCPU) in D:\a\ETWAnalyzer\ETWAnalyzer\ETWAnalyzer\EventDump\DumpCPUMethod.cs:line 418
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at ETWAnalyzer.Infrastructure.EnumerableSorterExtensions.SortAscendingGetTopNLast[TData,V](IEnumerable`1 data, Func`2 keyselector, Action`1 sortStatePreparer, SkipTakeRange topN) in D:\a\ETWAnalyzer\ETWAnalyzer\ETWAnalyzer\Infrastructure\EnumerableSorterExtensions.cs:line 41
   at ETWAnalyzer.EventDump.DumpCPUMethod.AddAndPrintTotalStats(List`1 matches, TestDataFile file) in D:\a\ETWAnalyzer\ETWAnalyzer\ETWAnalyzer\EventDump\DumpCPUMethod.cs:line 448
   at ETWAnalyzer.EventDump.DumpCPUMethod.ExecuteInternal() in D:\a\ETWAnalyzer\ETWAnalyzer\ETWAnalyzer\EventDump\DumpCPUMethod.cs:line 235
   at ETWAnalyzer.Commands.DumpCommand.Run() in D:\a\ETWAnalyzer\ETWAnalyzer\ETWAnalyzer\Commands\DumpCommand.cs:line 1769
   at ETWAnalyzer.Program.MainCore(String[] args) in D:\a\ETWAnalyzer\ETWAnalyzer\ETWAnalyzer\Program.cs:line 109
   at ETWAnalyzer.Program.Main(String[] args) in D:\a\ETWAnalyzer\ETWAnalyzer\ETWAnalyzer\Program.cs:line 69
```
**To Reproduce**
install etwanalyzer via nuget, run "ETWAnalyzer.exe -dump CPU -filedir D:\Etw-Extract"

**Expected behavior**
no exception shall happen

**Screenshots**
n.a.

**Comment by AloisKraus** [comment]
This is by intention. The Nuget package is meant to consume extracted Json files which does not need any configuration files for extraction.

If you want to extract you should use one of the Released packages for .NET 4.8 or .NET 6.0 which contains also the config files. 
Nuget is not meant to distribute executable tools with configs. This would also be bad if you create your custom configuration files which would be overwritten by the package. The only way to cleanly solve this is to not provide config files with the Nuget package. 

But if you want to you use the Nuget package and copy the configs from one of the releases.

**Comment by wtjwtjwtj** [comment]
Understood.
Thanks for the fast reply. :-)
