### ISSUE TITLE
ArgumentOutOfRangeException in Microsoft.Windows.EventTracing.Power.ProcessorFrequencyObjectContext.GetAverageFrequency

### ISSUE THREAD

**Issue by AloisKraus** [Siemens-Healthineers/ETWAnalyzer#91]
Some ETW Data does lead to exceptions while retrieving CPU frequency:

```
 ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.SZArrayHelper.get_Item[T](Int32 index)
   at Microsoft.Windows.EventTracing.Power.ProcessorFrequencyObjectContext.GetAverageFrequency(ProcessorFrequencyIntervalFlyweight flyweight)
   at ETWAnalyzer.Extractors.CPU.CpuFrequencyExtractor.Extract(ITraceProcessor processor, ETWExtract results) in D:\a\ETWAnalyzer\ETWAnalyzer\ETWAnalyzer\Extractors\CPU\CpuFrequencyExtractor.cs:line 32
   at ETWAnalyzer.Extractors.ExtractSingleFile.Execute(OutDir outputDirectory, Boolean haveToDeleteTemp) in D:\a\ETWAnalyzer\ETWAnalyzer\ETWAnalyzer\Extractors\ExtractSingleFile.cs:line 211

```

**Comment by AloisKraus** [comment]
Fixed with 98a5f800505f4cd4838a976be2850911c7f0e086
